version: "3"
services:
  postgres:
    container_name: challenge_postgres
    image: postgres:alpine
    volumes:
      - challenge_pg:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - challenge-network
      - pgadmin-network
  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4
    volumes:
      - pgadmin4:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=coding@challenge.org
      - PGADMIN_DEFAULT_PASSWORD=secret
    ports:
      - "5050:80"
    networks:
      - pgadmin-network
networks:
  challenge-network:
    driver: bridge
  pgadmin-network:
    driver: bridge
volumes:
  challenge_pg:
  pgadmin4:
