version: "3"
services:
  tests:
    image: maven:3.6-jdk-8
    stop_signal: SIGKILL
    working_dir: /usr
    volumes:
      - ./src:/usr/src
      - ./pom.xml:/usr/pom.xml
      - /var/run/docker.sock:/var/run/docker.sock
    command: mvn test
  postgres:
    container_name: treeservice-postgres
    image: postgres:alpine
    volumes:
      - treeservice-pg:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
    networks:
      - treeservice-network
    depends_on:
      - tests
  treeservice:
    container_name: treeservice
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - postgres
      - tests
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - treeservice-network
networks:
  treeservice-network:
volumes:
  treeservice-pg:
